title: Recaf documentation
description: Documentation for Recaf, the modern bytecode editor
logourl: https://github.com/Col-E/Recaf
url: "localhost:4000"
#url: "coley.software/recaf-documentation"
gems:
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
remote_theme: Col-E/Jekyll-Obsidian-Theme